### ISSUE TITLE
Email regex matching throws TypeError

### ISSUE THREAD

**Issue by CarpathianUA** [AdventielFr/terraform-aws-iam-rotate-credentials#1]
Hi,

Thanks for the nice module, it's very useful!
There is a bug with regex matching here:
https://github.com/AdventielFr/terraform-aws-iam-rotate-credentials/blob/f76e966b71024132058c9aa565775ca6280379ae/src/common.py#L94
It throws TypeError.
I've forked a repo and fixed it by changing:
```
match = re.match(r"^[a-zA-Z0-9_.+-]+@([a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+)$", request.email)
```
I can open a PR for that if it's acceptable. Or just use the fix :)
Thanks

**Comment by gwendallg** [comment]
Hi, 
You can open a PR,

Thanks
